include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - lib/**.g.dart

linter:
  rules:
    library_private_types_in_public_api: false
    no_default_cases: false
    public_member_api_docs: false
    require_trailing_commas: false
    specify_nonobvious_property_types: false
